# Generated by Django 5.1.1 on 2024-09-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('director', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('reviews', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='movie_images/')),
            ],
        ),
    ]
